import 'package:get/get.dart';

class AppLocalizations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'id_ID': {
          'win.text': 'Pengumuman Pemenang',
          'setting': 'Pengaturan',
          'edit.score': 'Ubah Skor',
          'start': 'Mulai',
          'stop': 'Berhenti',
          'reset': 'Reset',
          'label.board': 'Label Board',
          'text': 'Teks ',
          'right': 'Kanan',
          'left': 'Kiri',
          'max': 'Maksimal ',
          'empty.value': 'Nilai Kosong',
          'color.board': 'Warna Board : ',
          'increment': 'Nilai Naik',
          'limit.max': 'Limit Maksimal',
          'timer': 'Timer Waktu',
          'change.language': 'Ubah Bahasa',
          'digit.size': 'Ukuran Angka',
          'small': 'Kecil',
          'default': 'Default',
          'large': 'Besar',
          'restore': 'Pulihkan Pembayaran',
          'title.ads': 'Versi Bebas Iklan',
          'msg.ads': 'Hapus semua iklan dari aplikasi ini.',
          'buy.now': 'Beli Sekarang',
          'zero.value': 'Lebih dari 0',
        },
        'en_US': {
          'win.text': 'Winner Announcement',
          'setting': 'Edit Score',
          'start': 'Start',
          'stop': 'Stop',
          'reset': 'Reset',
          'label.board': 'Board Label',
          'text': 'Text ',
          'right': 'Right',
          'left': 'Right',
          'max': 'Maximum ',
          'empty.value': 'Empty Value',
          'color.board': 'Board Color : ',
          'increment': 'Value Up',
          'limit.max': 'Maximum Limit',
          'timer': 'Timer',
          'change.language': 'Change Language',
          'digit.size': 'Digit Size',
          'small': 'Small',
          'default': 'Default',
          'large': 'Large',
          'restore': 'Restore Purchase',
          'title.ads': 'Ad Free Version',
          'msg.ads': 'Remove all advertisements form this app.',
          'buy.now': 'Buy Now',
          'zero.value': 'More then 0',
        }
      };
}